export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';

export const AUTH_SAML_LOGIN_FAIL = 'AUTH_SAML_LOGIN_FAIL';
export const AUTH_SAML_LOGIN_REQUEST = 'AUTH_SAML_LOGIN_REQUEST';
export const AUTH_SAML_LOGIN_SUCCESS = 'AUTH_SAML_LOGIN_SUCCESS';

export const AUTH_ME_FAIL = 'AUTH_ME_FAIL';
export const AUTH_ME_REQUEST = 'AUTH_ME_REQUEST';
export const AUTH_ME_SUCCESS = 'AUTH_ME_SUCCESS';

export const AUTH_LOGOUT_REQUEST = 'AUTH_LOGOUT_REQUEST';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';

export const AUTH_TOKEN_REFRESH_REQUEST = 'AUTH_TOKEN_REFRESH_REQUEST';

export const AUTH_PASSWORD_FORGOT_REQUEST = 'AUTH_PASSWORD_FORGOT_REQUEST';
export const AUTH_PASSWORD_FORGOT_SUCCESS = 'AUTH_PASSWORD_FORGOT_SUCCESS';
export const AUTH_PASSWORD_FORGOT_FAIL = 'AUTH_PASSWORD_FORGOT_FAIL';
export const AUTH_PASSWORD_FORGOT_RESET = 'AUTH_PASSWORD_FORGOT_RESET';

export const AUTH_VERIFICATION_CODE_RESEND = 'AUTH_VERIFICATION_CODE_RESEND';
export const AUTH_VERIFICATION_CODE_VERIFY_REQUEST =
  'AUTH_VERIFICATION_CODE_VERIFY_REQUEST';
export const AUTH_VERIFICATION_CODE_VERIFY_SUCCESS =
  'AUTH_VERIFICATION_CODE_VERIFY_SUCCESS';
export const AUTH_VERIFICATION_CODE_VERIFY_FAIL =
  'AUTH_VERIFICATION_CODE_VERIFY_FAIL';
export const AUTH_PASSWORD_CHANGE_REQUEST = 'AUTH_PASSWORD_CHANGE_REQUEST';
export const AUTH_PASSWORD_CHANGE_SUCCESS = 'AUTH_PASSWORD_CHANGE_SUCCESS';
export const AUTH_PASSWORD_CHANGE_FAIL = 'AUTH_PASSWORD_CHANGE_FAIL';

export const AUTH_OID_STORE_USER = 'AUTH_OID_STORE_USER';

// DirectoryLayout All Employees
export const ALL_EMPLOYEES_REQUEST = 'ALL_EMPLOYEES_REQUEST';
export const ALL_EMPLOYEES_SUCCESS = 'ALL_EMPLOYEES_SUCCESS';
export const ALL_EMPLOYEES_ERROR = 'ALL_EMPLOYEES_ERROR';

// Applications
export const APPS_FETCH_ALL_FAIL = 'APPS_FETCH_ALL_FAIL';
export const APPS_FETCH_ALL_REQUEST = 'APPS_FETCH_ALL_REQUEST';
export const APPS_FETCH_ALL_SUCCESS = 'APPS_FETCH_ALL_SUCCESS';

export const APPS_FETCH_APP_NAME_REQUEST = 'APPS_FETCH_APP_NAME_REQUEST';
export const APPS_FETCH_APP_NAME_SUCCESS = 'APPS_FETCH_APP_NAME_SUCCESS';
export const APPS_FETCH_APP_NAME_FAIL = 'APPS_FETCH_APP_NAME_FAIL';
